Traceback (most recent call last):
  File "/home/user/webapp/app.py", line 1, in <module>
    from flask import Flask, render_template, request, jsonify
ModuleNotFoundError: No module named 'flask'
Traceback (most recent call last):
  File "/home/user/webapp/app.py", line 1, in <module>
    from flask import Flask, render_template, request, jsonify
ModuleNotFoundError: No module named 'flask'
Traceback (most recent call last):
  File "/home/user/webapp/app.py", line 1, in <module>
    from flask import Flask, render_template, request, jsonify
ModuleNotFoundError: No module named 'flask'
Traceback (most recent call last):
  File "/home/user/webapp/app.py", line 1, in <module>
    from flask import Flask, render_template, request, jsonify
ModuleNotFoundError: No module named 'flask'
Traceback (most recent call last):
  File "/home/user/webapp/app.py", line 1, in <module>
    from flask import Flask, render_template, request, jsonify
ModuleNotFoundError: No module named 'flask'
Traceback (most recent call last):
  File "/home/user/webapp/app.py", line 1, in <module>
    from flask import Flask, render_template, request, jsonify
ModuleNotFoundError: No module named 'flask'
Traceback (most recent call last):
  File "/home/user/webapp/app.py", line 1, in <module>
    from flask import Flask, render_template, request, jsonify
ModuleNotFoundError: No module named 'flask'
Traceback (most recent call last):
  File "/home/user/webapp/app.py", line 1, in <module>
    from flask import Flask, render_template, request, jsonify
ModuleNotFoundError: No module named 'flask'
Traceback (most recent call last):
  File "/home/user/webapp/app.py", line 1, in <module>
    from flask import Flask, render_template, request, jsonify
ModuleNotFoundError: No module named 'flask'
[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://169.254.0.21:5000
[33mPress CTRL+C to quit[0m
 * Restarting with watchdog (inotify)
 * Debugger is active!
 * Debugger PIN: 903-792-757
[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://169.254.0.21:5000
[33mPress CTRL+C to quit[0m
 * Restarting with watchdog (inotify)
 * Debugger is active!
 * Debugger PIN: 903-792-757
10.12.63.232 - - [03/Sep/2025 03:33:31] "GET / HTTP/1.1" 200 -
10.12.63.232 - - [03/Sep/2025 03:33:31] "GET /static/js/main.js HTTP/1.1" 200 -
10.12.63.232 - - [03/Sep/2025 03:33:31] "GET /static/css/style.css HTTP/1.1" 200 -
10.12.63.232 - - [03/Sep/2025 03:33:31] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
10.12.63.232 - - [03/Sep/2025 03:34:04] "POST /result HTTP/1.1" 200 -
10.12.63.232 - - [03/Sep/2025 03:34:05] "GET /static/css/result.css HTTP/1.1" 200 -
10.12.63.232 - - [03/Sep/2025 03:34:05] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
10.12.63.232 - - [03/Sep/2025 03:34:24] "[35m[1mGET /basic_report?name=ÁπîÁî∞%20Ââõ&archetype=ÊÉÖÁÜ±ÁöÑÂâµÈÄ†ËÄÖ HTTP/1.1[0m" 500 -
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 1536, in __call__
    return self.wsgi_app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 1514, in wsgi_app
    response = self.handle_exception(e)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/webapp/app.py", line 327, in basic_report_page
    return render_template('basic_report.html')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/jinja2/environment.py", line 1295, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.12/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/user/webapp/templates/basic_report.html", line 6, in top-level template code
    <title>ASTRO-BODY TYPE REPORT - {{ archetype.name }}</title>
  File "/usr/local/lib/python3.12/site-packages/jinja2/environment.py", line 490, in getattr
    return getattr(obj, attribute)
           ^^^^^^^^^^^^^^^^^^^^^^^
jinja2.exceptions.UndefinedError: 'archetype' is undefined
10.12.63.232 - - [03/Sep/2025 03:34:24] "GET /basic_report?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
10.12.63.232 - - [03/Sep/2025 03:34:24] "GET /basic_report?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
10.12.63.232 - - [03/Sep/2025 03:34:25] "GET /basic_report?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
10.12.63.232 - - [03/Sep/2025 03:34:45] "GET / HTTP/1.1" 200 -
10.12.63.232 - - [03/Sep/2025 03:34:45] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
10.12.63.232 - - [03/Sep/2025 03:34:45] "[36mGET /static/js/main.js HTTP/1.1[0m" 304 -
10.12.63.232 - - [03/Sep/2025 03:35:32] "POST /result HTTP/1.1" 200 -
10.12.63.232 - - [03/Sep/2025 03:35:32] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
10.12.63.232 - - [03/Sep/2025 03:35:32] "[36mGET /static/css/result.css HTTP/1.1[0m" 304 -
10.12.63.232 - - [03/Sep/2025 03:35:42] "[35m[1mGET /basic_report?name=ÁπîÁî∞Ââõ&archetype=Ëá™Áî±„Å™„ÇãÊÄùÊÉ≥ÂÆ∂ HTTP/1.1[0m" 500 -
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 1536, in __call__
    return self.wsgi_app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 1514, in wsgi_app
    response = self.handle_exception(e)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/webapp/app.py", line 327, in basic_report_page
    return render_template('basic_report.html')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/jinja2/environment.py", line 1295, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.12/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/user/webapp/templates/basic_report.html", line 6, in top-level template code
    <title>ASTRO-BODY TYPE REPORT - {{ archetype.name }}</title>
  File "/usr/local/lib/python3.12/site-packages/jinja2/environment.py", line 490, in getattr
    return getattr(obj, attribute)
           ^^^^^^^^^^^^^^^^^^^^^^^
jinja2.exceptions.UndefinedError: 'archetype' is undefined
10.12.63.232 - - [03/Sep/2025 03:35:42] "[36mGET /basic_report?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1[0m" 304 -
10.12.63.232 - - [03/Sep/2025 03:35:42] "[36mGET /basic_report?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1[0m" 304 -
 * Detected change in '/home/user/webapp/app.py', reloading
 * Detected change in '/home/user/webapp/app.py', reloading
 * Detected change in '/home/user/webapp/app.py', reloading
 * Restarting with watchdog (inotify)
 * Debugger is active!
 * Debugger PIN: 903-792-757
 * Detected change in '/home/user/webapp/app.py', reloading
 * Detected change in '/home/user/webapp/app.py', reloading
 * Detected change in '/home/user/webapp/app.py', reloading
 * Restarting with watchdog (inotify)
 * Debugger is active!
 * Debugger PIN: 903-792-757
[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://169.254.0.21:5000
[33mPress CTRL+C to quit[0m
 * Restarting with watchdog (inotify)
 * Debugger is active!
 * Debugger PIN: 903-792-757
10.12.63.232 - - [03/Sep/2025 03:40:45] "GET / HTTP/1.1" 200 -
10.12.63.232 - - [03/Sep/2025 03:40:45] "[36mGET /static/js/main.js HTTP/1.1[0m" 304 -
10.12.63.232 - - [03/Sep/2025 03:40:45] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
10.12.63.232 - - [03/Sep/2025 03:41:15] "POST /result HTTP/1.1" 200 -
10.12.63.232 - - [03/Sep/2025 03:41:15] "[36mGET /static/css/result.css HTTP/1.1[0m" 304 -
10.12.63.232 - - [03/Sep/2025 03:41:15] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
10.12.63.232 - - [03/Sep/2025 03:41:19] "GET /basic_report?name=ÁπîÁî∞Ââõ&archetype=ÊÉÖÁÜ±ÁöÑÂâµÈÄ†ËÄÖ HTTP/1.1" 200 -
10.12.63.232 - - [03/Sep/2025 03:41:19] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
10.12.63.232 - - [03/Sep/2025 03:41:19] "[33mGET /static/css/report.css HTTP/1.1[0m" 404 -
10.12.63.232 - - [03/Sep/2025 03:41:34] "GET / HTTP/1.1" 200 -
10.12.63.232 - - [03/Sep/2025 03:41:34] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
10.12.63.232 - - [03/Sep/2025 03:41:34] "[36mGET /static/js/main.js HTTP/1.1[0m" 304 -
10.12.63.232 - - [03/Sep/2025 03:42:17] "POST /result HTTP/1.1" 200 -
10.12.63.232 - - [03/Sep/2025 03:42:18] "[36mGET /static/css/result.css HTTP/1.1[0m" 304 -
10.12.63.232 - - [03/Sep/2025 03:42:18] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
10.12.63.232 - - [03/Sep/2025 03:42:24] "GET /basic_report?name=Â∞èÁî∞ÁøîÂ≠ê&archetype=ÊÖàÊÑõ„Å™„ÇãËÇ≤ÊàêËÄÖ HTTP/1.1" 200 -
10.12.63.232 - - [03/Sep/2025 03:42:24] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
10.12.63.232 - - [03/Sep/2025 03:42:24] "[33mGET /static/css/report.css HTTP/1.1[0m" 404 -
 * Detected change in '/home/user/webapp/app.py', reloading
 * Detected change in '/home/user/webapp/app.py', reloading
 * Detected change in '/home/user/webapp/app.py', reloading
 * Restarting with watchdog (inotify)
 * Debugger is active!
 * Debugger PIN: 903-792-757
 * Detected change in '/home/user/webapp/app.py', reloading
 * Detected change in '/home/user/webapp/app.py', reloading
 * Detected change in '/home/user/webapp/app.py', reloading
 * Restarting with watchdog (inotify)
 * Debugger is active!
 * Debugger PIN: 903-792-757
 * Detected change in '/home/user/webapp/app.py', reloading
 * Detected change in '/home/user/webapp/app.py', reloading
 * Detected change in '/home/user/webapp/app.py', reloading
 * Restarting with watchdog (inotify)
 * Debugger is active!
 * Debugger PIN: 903-792-757
 * Detected change in '/home/user/webapp/app.py', reloading
 * Detected change in '/home/user/webapp/app.py', reloading
 * Detected change in '/home/user/webapp/app.py', reloading
 * Restarting with watchdog (inotify)
 * Debugger is active!
 * Debugger PIN: 903-792-757
 * Detected change in '/home/user/webapp/app.py', reloading
 * Detected change in '/home/user/webapp/app.py', reloading
 * Detected change in '/home/user/webapp/app.py', reloading
 * Restarting with watchdog (inotify)
 * Debugger is active!
 * Debugger PIN: 903-792-757
[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://169.254.0.21:5000
[33mPress CTRL+C to quit[0m
 * Restarting with watchdog (inotify)
 * Debugger is active!
 * Debugger PIN: 903-792-757
